---
- hosts: mywebserver
  tasks:
  - name: i want to install java on ubuntu nodes
    apt:
      name: "{{openjdk-8-jdk}}" 
      state: present
    when: ansible_os_family =="Debian"


  - name: i want to install java on redhat nodes
    apt:
     name:
     state: present
    when: ansible_os_family =="Redhat"  