---
- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install webserver on ubuntu nodes
    apt:
      name: "{{nagendrawebpackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: i want to start webserver on ubuntu nodes
    service:
      name: "{{nagendrawebpackonubuntu}}"
      state: started 
    when: ansible_os_family =="Debian"   

  - name: i want to install webserver on Redhat nodes
    ansible.builtin.dnf: 
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family =="Redhat"
  - name: i want to start webserver on Redhat nodes
    service:
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family =="redhat"  